import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:lucide_icons/lucide_icons.dart';
import '../../../core/theme/app_theme.dart';
import '../providers/profile_provider.dart';
import 'package:intl/intl.dart';

class PortfolioScreen extends ConsumerWidget {
  final String username;
  const PortfolioScreen({super.key, required this.username});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final portfolioState = ref.watch(portfolioProvider(username));

    return Scaffold(
      backgroundColor: Colors.white,
      appBar: AppBar(
        backgroundColor: Colors.white,
        elevation: 0,
        leading: IconButton(
          icon: const Icon(LucideIcons.chevronLeft, color: Colors.black),
          onPressed: () => Navigator.pop(context),
        ),
        actions: [
          IconButton(
            icon: const Icon(LucideIcons.share2, color: Colors.black),
            onPressed: () {},
          ),
        ],
      ),
      body: portfolioState.when(
        loading: () => const Center(child: CircularProgressIndicator(color: Colors.blueAccent)),
        error: (e, st) => Center(child: Text('Record Not Found : $e')),
        data: (profile) => SingleChildScrollView(
          padding: const EdgeInsets.symmetric(horizontal: 24, vertical: 32),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              // 1. Digital Header
              _PortfolioHeader(profile: profile),
              const SizedBox(height: 48),

              // 2. Career Objective
              if (profile.careerObjective != null) ...[
                _SectionTitle(title: 'Career Objective'),
                const SizedBox(height: 12),
                Text(
                  profile.careerObjective!,
                  style: const TextStyle(fontSize: 14, height: 1.6, color: Colors.black87, fontWeight: FontWeight.w500),
                ),
                const SizedBox(height: 40),
              ],

              // 3. Technical Skills
              if (profile.techSkills != null && profile.techSkills!.isNotEmpty) ...[
                _SectionTitle(title: 'Technical Competencies'),
                const SizedBox(height: 16),
                _SkillsGrid(skills: profile.techSkills!),
                const SizedBox(height: 40),
              ],

              // 4. Experience Timeline
              if (profile.experience != null && profile.experience!.isNotEmpty) ...[
                _SectionTitle(title: 'Professional Experience'),
                const SizedBox(height: 16),
                ...profile.experience!.map((exp) => _ExperienceItem(exp: exp)),
                const SizedBox(height: 32),
              ],

              // 5. Academic Records
              if (profile.education != null && profile.education!.isNotEmpty) ...[
                _SectionTitle(title: 'Educational History'),
                const SizedBox(height: 16),
                _EducationTable(education: profile.education!),
                const SizedBox(height: 40),
              ],

              // Footer
              const Center(
                child: Text(
                  'GENERATED BY ALLUMNOVA PORTFOLIO ENGINE',
                  style: TextStyle(fontSize: 8, fontWeight: FontWeight.w900, color: Colors.black12, letterSpacing: 2),
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}

class _SectionTitle extends StatelessWidget {
  final String title;
  const _SectionTitle({required this.title});

  @override
  Widget build(BuildContext context) {
    return Container(
      width: double.infinity,
      padding: const EdgeInsets.only(bottom: 8),
      decoration: const BoxDecoration(
        border: Border(bottom: BorderSide(color: Colors.black, width: 2)),
      ),
      child: Text(
        title.toUpperCase(),
        style: const TextStyle(fontSize: 14, fontWeight: FontWeight.w900, letterSpacing: 1.5, color: Colors.black),
      ),
    );
  }
}

class _PortfolioHeader extends StatelessWidget {
  final UserProfile profile;
  const _PortfolioHeader({required this.profile});

  @override
  Widget build(BuildContext context) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text(
          profile.name.toUpperCase(),
          style: const TextStyle(fontSize: 32, fontWeight: FontWeight.w900, letterSpacing: -1, color: Colors.black),
        ),
        const SizedBox(height: 8),
        Row(
          children: [
            Text(
              '${profile.department ?? "INSTITUTIONAL MEMBER"}  |  ${profile.role?.toUpperCase() ?? "MEMBER"}',
              style: const TextStyle(fontSize: 10, fontWeight: FontWeight.w900, color: Colors.black54, letterSpacing: 1),
            ),
            const Spacer(),
            _TierBadge(tier: profile.tierLevel ?? 'Echo'),
          ],
        ),
        const SizedBox(height: 16),
        Wrap(
          spacing: 16,
          runSpacing: 8,
          children: [
            _MetaSignal(icon: LucideIcons.mail, value: 'INSTITUTIONAL MAIL'),
            if (profile.location != null) _MetaSignal(icon: LucideIcons.mapPin, value: profile.location!),
            if (profile.linkedIn != null) _MetaSignal(icon: LucideIcons.linkedin, value: 'LINKEDIN'),
          ],
        ),
      ],
    );
  }
}

class _MetaSignal extends StatelessWidget {
  final IconData icon;
  final String value;
  const _MetaSignal({required this.icon, required this.value});

  @override
  Widget build(BuildContext context) {
    return Row(
      mainAxisSize: MainAxisSize.min,
      children: [
        Icon(icon, size: 12, color: Colors.black26),
        const SizedBox(width: 6),
        Text(value, style: const TextStyle(fontSize: 10, fontWeight: FontWeight.w600, color: Colors.black45)),
      ],
    );
  }
}

class _TierBadge extends StatelessWidget {
  final String tier;
  const _TierBadge({required this.tier});

  @override
  Widget build(BuildContext context) {
    return Container(
      padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 4),
      decoration: BoxDecoration(
        color: Colors.blueAccent.withOpacity(0.1),
        borderRadius: BorderRadius.circular(4),
        border: Border.all(color: Colors.blueAccent.withOpacity(0.2)),
      ),
      child: Text(
        '$tier INNOVATOR',
        style: const TextStyle(fontSize: 8, fontWeight: FontWeight.w900, color: Colors.blueAccent),
      ),
    );
  }
}

class _SkillsGrid extends StatelessWidget {
  final Map<String, dynamic> skills;
  const _SkillsGrid({required this.skills});

  @override
  Widget build(BuildContext context) {
    return Column(
      children: skills.entries.map((entry) => Padding(
        padding: const EdgeInsets.only(bottom: 8),
        child: Row(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            SizedBox(
              width: 100,
              child: Text(
                '${entry.key}:',
                style: const TextStyle(fontSize: 12, fontWeight: FontWeight.w900, color: Colors.black),
              ),
            ),
            Expanded(
              child: Text(
                entry.value.toString(),
                style: const TextStyle(fontSize: 12, color: Colors.black87, height: 1.4),
              ),
            ),
          ],
        ),
      )).toList(),
    );
  }
}

class _ExperienceItem extends StatelessWidget {
  final Experience exp;
  const _ExperienceItem({required this.exp});

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.only(bottom: 24),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            children: [
              Text(exp.company.toUpperCase(), style: const TextStyle(fontSize: 14, fontWeight: FontWeight.w900, color: Colors.black)),
              Text(
                '${exp.startDate.year} - ${exp.isCurrent ? "PRESENT" : exp.endDate?.year}',
                style: const TextStyle(fontSize: 10, fontWeight: FontWeight.w900, color: Colors.black26),
              ),
            ],
          ),
          const SizedBox(height: 4),
          Text(exp.position, style: const TextStyle(fontSize: 12, fontWeight: FontWeight.w900, color: Colors.blueAccent)),
          const SizedBox(height: 8),
          Text(exp.description, style: const TextStyle(fontSize: 12, color: Colors.black54, height: 1.5)),
        ],
      ),
    );
  }
}

class _EducationTable extends StatelessWidget {
  final List<Education> education;
  const _EducationTable({required this.education});

  @override
  Widget build(BuildContext context) {
    return Container(
      decoration: BoxDecoration(
        border: Border.all(color: Colors.black12),
      ),
      child: Table(
        border: TableBorder.symmetric(inside: const BorderSide(color: Colors.black12)),
        children: [
          const TableRow(
            decoration: BoxDecoration(color: Color(0xFFF8FAFC)),
            children: [
              _TableCell(text: 'INSTITUTE', isHeader: true),
              _TableCell(text: 'DEGREE', isHeader: true),
              _TableCell(text: 'YEAR', isHeader: true),
            ],
          ),
          ...education.map((edu) => TableRow(
            children: [
              _TableCell(text: edu.school),
              _TableCell(text: edu.degree),
              _TableCell(text: edu.endDate?.year.toString() ?? edu.startDate.year.toString()),
            ],
          )),
        ],
      ),
    );
  }
}

class _TableCell extends StatelessWidget {
  final String text;
  final bool isHeader;
  const _TableCell({required this.text, this.isHeader = false});

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.all(12),
      child: Text(
        text,
        style: TextStyle(
          fontSize: 10,
          fontWeight: isHeader ? FontWeight.w900 : FontWeight.w600,
          color: isHeader ? Colors.black : Colors.black87,
        ),
      ),
    );
  }
}
